modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"
[[mods]]
modId = "poscendo"
version = "${file.jarVersion}"
displayName = "Poscendo"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="alchemistry.png"
#credits="Thanks for this example mod goes to Java"
#authors="Love, Cheese and small house plants"
#displayTest="MATCH_VERSION"

description = '''
A configurable clientside mod adding various tweaks to potions.
'''

[[dependencies.poscendo]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.poscendo]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
